openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
tags:
- name: Item API
  description: Item operations
- name: Public Category API
  description: Public category operations
- name: Public Item API
  description: Public item operations
paths:
  /api/v1/items/{id}:
    put:
      tags:
      - Item API
      summary: Update an existing item
      description: Updates an item with the provided data
      operationId: updateItem
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ItemRequest"
        required: true
      responses:
        "200":
          description: Item updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemResponse"
        "400":
          description: Invalid input data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemResponse"
        "404":
          description: Item not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemResponse"
    delete:
      tags:
      - Item API
      summary: Delete an item
      description: Soft deletes an item by marking it as inactive
      operationId: deleteItem
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "204":
          description: Item deleted successfully
        "404":
          description: Item not found
  /api/v1/items:
    post:
      tags:
      - Item API
      summary: Create a new item
      description: Creates a new item with the provided data
      operationId: createItem
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ItemRequest"
        required: true
      responses:
        "201":
          description: Item created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemResponse"
        "400":
          description: Invalid input data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemResponse"
        "422":
          description: Item could not be processed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemResponse"
  /api/v1/items/batch:
    post:
      tags:
      - Item API
      summary: Batch create items
      description: Creates multiple items in a single request for better performance
      operationId: batchCreateItems
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/ItemRequest"
        required: true
      responses:
        "201":
          description: Items created successfully
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
        "400":
          description: Invalid input data
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
  /api/v1/public/items:
    get:
      tags:
      - Public Item API
      summary: Get paginated list of available items
      description: Retrieves a paginated list of items that are active and not taken
      operationId: getItems
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
          minimum: 0
      - name: size
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 10
          maximum: 100
          minimum: 1
      - name: sortBy
        in: query
        required: false
        schema:
          type: string
          default: postedOn
      - name: direction
        in: query
        required: false
        schema:
          type: string
          default: desc
      responses:
        "200":
          description: Available items retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageItemResponse"
  /api/v1/public/items/{id}:
    get:
      tags:
      - Public Item API
      summary: Get item by ID
      description: Retrieves an item by its unique identifier
      operationId: getItemById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Item found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemResponse"
        "404":
          description: Item not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemResponse"
  /api/v1/public/items/search:
    get:
      tags:
      - Public Item API
      summary: Search items by keyword
      description: Searches for items containing the specified keyword in title or
        description
      operationId: searchItems
      parameters:
      - name: keyword
        in: query
        required: true
        schema:
          type: string
      - name: pageable
        in: query
        required: true
        schema:
          $ref: "#/components/schemas/Pageable"
      responses:
        "200":
          description: Search completed successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageItemResponse"
  /api/v1/public/items/category/{categoryId}:
    get:
      tags:
      - Public Item API
      summary: Get items by category
      description: Retrieves a paginated list of items in the specified category
      operationId: getItemsByCategory
      parameters:
      - name: categoryId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: pageable
        in: query
        required: true
        schema:
          $ref: "#/components/schemas/Pageable"
      responses:
        "200":
          description: Items retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageItemResponse"
        "404":
          description: Category not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageItemResponse"
  /api/v1/ping:
    get:
      tags:
      - ping-controller
      operationId: ping
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
  /api/v1/items/{id}/available:
    get:
      tags:
      - Item API
      summary: Check if an item is available
      description: "Checks if an item exists, is active, and not taken"
      operationId: isItemAvailable
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Availability check completed
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
  /api/v1/items/user/{userId}:
    get:
      tags:
      - Item API
      summary: Get all items from a specific user
      description: Retrieves all active items posted by the specified user
      operationId: getUserItems
      responses:
        "200":
          description: Items retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ItemResponse"
        "404":
          description: User not found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ItemResponse"
  /api/v1/items/type/{itemType}:
    get:
      tags:
      - Item API
      summary: Get items by type
      description: Retrieves a paginated list of items of the specified type (INTERNAL
        or EXTERNAL)
      operationId: getItemsByType
      parameters:
      - name: itemType
        in: path
        required: true
        schema:
          type: string
          enum:
          - INTERNAL
          - EXTERNAL
      - name: pageable
        in: query
        required: true
        schema:
          $ref: "#/components/schemas/Pageable"
      responses:
        "200":
          description: Items retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageItemResponse"
        "400":
          description: Invalid item type
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageItemResponse"
  /api/v1/categories:
    get:
      tags:
      - Public Category API
      summary: Get all categories
      description: Retrieves a list of all categories
      operationId: getAllCategories
      responses:
        "200":
          description: Categories retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CategoryResponse"
  /api/v1/categories/{id}:
    get:
      tags:
      - Public Category API
      summary: Get category by ID
      description: Retrieves a category by its unique identifier
      operationId: getCategoryById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Category found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CategoryResponse"
        "404":
          description: Category not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CategoryResponse"
  /api/v1/categories/{id}/subcategories:
    get:
      tags:
      - Public Category API
      summary: Get subcategories by parent ID
      description: Retrieves a list of subcategories for a given parent category ID
      operationId: getSubcategories
      parameters: []
      responses:
        "200":
          description: Subcategories retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CategoryResponse"
        "404":
          description: Parent category not found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CategoryResponse"
  /api/v1/categories/root:
    get:
      tags:
      - Public Category API
      summary: Get root categories
      description: Retrieves a list of all root categories (categories without a parent)
      operationId: getRootCategories
      responses:
        "200":
          description: Root categories retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CategoryResponse"
  /api/v1/categories/featured:
    get:
      tags:
      - Public Category API
      summary: Get featured categories
      description: Retrieves a list of featured categories
      operationId: getFeaturedCategories
      responses:
        "200":
          description: Featured categories retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CategoryResponse"
components:
  schemas:
    ItemRequest:
      type: object
      properties:
        title:
          type: string
          maxLength: 150
          minLength: 0
        description:
          type: string
          minLength: 1
        condition:
          type: string
          enum:
          - NEW
          - LIKE_NEW
          - USED
          - DEFECTIVE
        address:
          type: string
          minLength: 1
        imageUrl:
          type: string
          minLength: 1
        categoryId:
          type: integer
          format: int64
        pickupPossible:
          type: boolean
        deliveryPossible:
          type: boolean
      required:
      - categoryId
      - condition
    CategoryResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        parentId:
          type: integer
          format: int64
        parentTitle:
          type: string
        createdAt:
          type: string
          format: date-time
        active:
          type: boolean
    ItemResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        condition:
          type: string
          enum:
          - NEW
          - LIKE_NEW
          - USED
          - DEFECTIVE
        address:
          type: string
        postedOn:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        imageUrl:
          type: string
        itemType:
          type: string
          enum:
          - INTERNAL
          - EXTERNAL
        externalUrl:
          type: string
        active:
          type: boolean
        owner:
          type: string
          format: uuid
        category:
          $ref: "#/components/schemas/CategoryResponse"
        sourceExternalPlatform:
          type: string
          enum:
          - ANIBIS
        pickupPossible:
          type: boolean
        deliveryPossible:
          type: boolean
    PageItemResponse:
      type: object
      properties:
        totalPages:
          type: integer
          format: int32
        totalElements:
          type: integer
          format: int64
        first:
          type: boolean
        last:
          type: boolean
        size:
          type: integer
          format: int32
        content:
          type: array
          items:
            $ref: "#/components/schemas/ItemResponse"
        number:
          type: integer
          format: int32
        sort:
          $ref: "#/components/schemas/SortObject"
        pageable:
          $ref: "#/components/schemas/PageableObject"
        numberOfElements:
          type: integer
          format: int32
        empty:
          type: boolean
    PageableObject:
      type: object
      properties:
        offset:
          type: integer
          format: int64
        sort:
          $ref: "#/components/schemas/SortObject"
        paged:
          type: boolean
        pageNumber:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        unpaged:
          type: boolean
    SortObject:
      type: object
      properties:
        empty:
          type: boolean
        sorted:
          type: boolean
        unsorted:
          type: boolean
    Pageable:
      type: object
      properties:
        page:
          type: integer
          format: int32
          minimum: 0
        size:
          type: integer
          format: int32
          minimum: 1
        sort:
          type: array
          items:
            type: string
